Sprint 6 solution
TimurPractic/java-kanban pull request #1
Opened 2024-03-31 21:03 UTC by TimurPractic

2024-04-01 09:16 UTC, kalitva requested changes

2024-04-01 09:16 UTC, kalitva commented on java-kanban.iml
Файлы intellij не должны храниться в репе - нужно их удалить, добавить в гитигнор и сделать коммит (intellij их потом опять сегенрит).

2024-04-01 09:16 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryHistoryManager.java
> +import java.util.*;
Не используй wildcard импорты.

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

Это затрудняет чтение, засоряет git diff'ы и иногда может служить причиной лишних конфликтов при мерже веток. Настрой intellij чтобы она не схлопывала импорты

https://blog.marcnuri.com/intellij-idea-how-to-disable-wildcard-imports

2024-04-01 09:16 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +        for (int i : tasks.keySet()) {
Для enhanced for loop имя `i` не используется, называй переменную исходя из того, что она хранит. В данном случае `id` или `taskId`

Поправь во всех похожих кейсах

2024-04-01 09:16 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +
Не нужна пустая линия после заголовка метода

2024-04-01 09:16 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +        int currEpicID = newSubTask.getEpicId();
`currEpicID --> currentEpicId`

1. Не используй сокращения
2. Camel Case

2024-04-01 09:16 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/model/Node.java
> +public class Node {
Объяви этот класс внутри хистори-менеджера как вложенный (`private static class ...`)

2024-04-01 16:53 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/model/Node.java
> +public class Node {
Fixed

2024-04-01 16:56 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +        int currEpicID = newSubTask.getEpicId();
Fixed

2024-04-01 16:57 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +
Fixed, странно, и я не заметил, и чекстайл пропустил)

2024-04-01 17:00 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +        for (int i : tasks.keySet()) {
Fixed
Поправил везде

2024-04-01 17:06 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryHistoryManager.java
> +import java.util.*;
Fixed, и в Idea отключил складывание

2024-04-01 17:49 UTC, TimurPractic commented on java-kanban.iml
Fixed

2024-04-02 15:15 UTC, kalitva approved these changes

2024-04-02 15:15 UTC, kalitva commented on .gitignore
> +java-kanban.iml
Лучше - `*.iml`

2024-04-02 15:15 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryHistoryManager.java
> +    private final Map<Integer, Node> historyMap = new HashMap<>();
Не используй в названиях коллекций (и методов соответственно) слова типа `List Map Set Array` и.т.п

`historyMap --> history или historyIndex`

2024-04-02 15:15 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryHistoryManager.java
> +    public ArrayList<Task> getTasks() {
`public List<Task> getTasks() {`

2024-04-02 15:15 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryHistoryManager.java
> +        public Task getTask() {
В геттерах и сеттерах теперь нет необходимости (к этим полям и так есть доступ внутри хистори-менеджера)

2024-04-02 15:15 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +        for (int taskId : tasks.keySet()) {
```java
tasks.keySet().forEach(historyManager::remove)
```

2024-04-03 20:03 UTC, merged