7 Sprint PR
TimurPractic/java-kanban pull request #2
Opened 2024-04-09 21:09 UTC by TimurPractic

Here will be added save to file feature

2024-05-11 16:58 UTC, kalitva requested changes

2024-05-11 16:58 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/exception/ManagerIOException.java
> +public class ManagerIOException extends Exception {
Нужно наследовать от `RuntimeException`

https://www.baeldung.com/java-checked-unchecked-exceptions

2024-05-11 16:58 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +    private String fileName = "filename.csv";
Имя файла должно приходить параметром конструктора

2024-05-11 16:58 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +        }
Поправь отступы

2024-05-11 16:58 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +        List<Epic> le = super.getEpics();
И назови эти переменные `tasks, subtasks, epics`

2024-05-11 16:58 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(Path path) throws NullPointerException {
Не надо декларировать `NullPointerException`

2024-05-11 16:58 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +                } catch (NullPointerException e) {
`NullPointerException` не перехватывается, если он вылетает, значит где-то баг

2024-05-11 16:58 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +                                System.out.println("Элемент истории с id=" + id + " не найден.");
Не используй `System.out.println` кроме как для дебага

2024-05-11 17:20 UTC, Ulgenfeurg commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +        }
Fixed

2024-05-11 17:21 UTC, Ulgenfeurg commented on src/ru/yandex/practicum/tasktracker/exception/ManagerIOException.java
> +public class ManagerIOException extends Exception {
Fixed

2024-05-11 17:29 UTC, Ulgenfeurg commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +                } catch (NullPointerException e) {
Fixed

2024-05-11 17:30 UTC, Ulgenfeurg commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(Path path) throws NullPointerException {
Fixed

2024-05-11 18:02 UTC, Ulgenfeurg commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +                                System.out.println("Элемент истории с id=" + id + " не найден.");
Fixed

2024-05-11 18:06 UTC, Ulgenfeurg commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +        List<Epic> le = super.getEpics();
Fixed

2024-05-11 18:38 UTC, Ulgenfeurg commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +    private String fileName = "filename.csv";
Fixed

2024-05-12 15:46 UTC, kalitva approved these changes

2024-05-12 15:46 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +    private static final String HAT = "id,type,title,status,description,epic";
`HAT --> CSV_HEADER` Переименуй более понятно

2024-05-12 15:46 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +    public static String historyToString(HistoryManager manager) {
А почему `public`? Эти методы где-то используются ероме этого класса?

2024-05-12 16:05 UTC, Ulgenfeurg commented on src/ru/yandex/practicum/tasktracker/manager/FileBackedTaskManager.java
> +    private static final String HAT = "id,type,title,status,description,epic";
Fixed

2024-05-12 16:10 UTC, merged