8 sprint
TimurPractic/java-kanban pull request #3
Opened 2024-06-11 20:09 UTC by TimurPractic

2024-06-13 13:28 UTC, Fleaman777 requested changes

2024-06-13 13:28 UTC, Fleaman777 commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +    private Set<Task> prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime,
как еще один альтернативный вариант объявления TreeSet для Task без явного просечивания компаратора, это классом Task импелментировать интерфейс Comparable

2024-06-13 13:28 UTC, Fleaman777 commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +            int newId = idSequence++;
Расчёт айдишника можно вынести в отдельный метод, что бы было удобней управлять логикой создания айдишника в одном месте

2024-06-13 13:28 UTC, Fleaman777 commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +                .min(Comparator.naturalOrder());
можно сразу добавить обработку Optional и возвращать объект если он есть. 

Optional - хорошо возвращать например из классов которые взаимодействуют с бд, а внутри приложения уже использовать объекты

2024-06-13 13:28 UTC, Fleaman777 commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +            Optional<LocalDateTime> minStartTime = subtasksStream
почему бы сразу не продолжать обработку optional в стриме без вынесения промежуточных результатов в локальные переменные?

2024-06-13 13:28 UTC, Fleaman777 commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +    public boolean validator(Task task) {
должен ли этот метод быть public?

2024-06-13 13:28 UTC, Fleaman777 commented on test/EpicTest.java
> +        InMemoryTaskManager taskManager = Managers.getDefault();
эту часть и др общие вещи можно вынести в метод с аннотацией @BeforeEach

2024-06-13 13:28 UTC, Fleaman777 commented on test/InMemoryTaskManagerTest.java
> +
исправленные тесты хорошие, правльные, 
но обрати внимание на те, которые необходимо реализовать по заданию и на структуру этой реализации (должен быть абстрактный класс abstract class TaskManagerTest<T extends TaskManager> и тд)

2024-06-16 19:00 UTC, TimurPractic commented
Привет! Спасибо за добрые слова, мне приятно, что моя работа не кривая)
Я вижу твои замечания, и готов их исправить, но есть небольшая загвоздка - некоторые из этих частей кода я сделал именно так, потому что мне велел так мделаьть предыдущий ревьюер, который смотрел мою работу на более ранних спринтах. Я буду отмечать такое на конкретном примере, и НЕ исправлять. Если ты считаешь, что прошлый ревьюер был не совсем прав, и всё же нужно поправить - просто оставь ещё один коммент, и я поправлю во второй итерации. 

Остальные я исправлю по твоим указаниям, спасибо за понятные комментарии)

2024-06-16 19:02 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +            int newId = idSequence++;
Это пришло от прошлого ревьюера, и я уже не очень помню как сделал в самом начале. Если надо - могу сделать метод, который будет генерировать id, и вызывать его везде где надо.

2024-06-16 19:22 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +            Optional<LocalDateTime> minStartTime = subtasksStream
Мне так проще смотреть на метод, когда я собираю его логику, и это позволяет явно указывать, с какими переменными идёт работа. Некоторые методы (как, например, этот, setEpicDuration) - довольно запутанные, и с таким вынесением я делаю его более понятным мне, и другим неопытным читателям. При этом на скорость, насколько я понимаю, это будет влиять только в высоконагруженных системах где много обращений в секунду к этой переменной.

Если всё же это обязательно -  я исправлю.

2024-06-16 19:24 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +    public boolean validator(Task task) {
Не должен) Возможно, такой излишне публичный метод у меня не один, я просто в плане публичности только за переменными слежу, а вот методы почему то все у меня public, на всякий случай.

Конкретно здесь - исправлено)

2024-06-16 19:36 UTC, TimurPractic commented on test/EpicTest.java
> +        InMemoryTaskManager taskManager = Managers.getDefault();
Сначала я так не сдела, потому что оно не работало. Сейчас был хороший повод разобраться почему)

Исправлено)

2024-06-16 21:16 UTC, TimurPractic commented on test/InMemoryTaskManagerTest.java
> +
Тесты добавил согласно списка, часть из того, что было в списке уже проверяется не в отдельном тесте

2024-06-16 21:29 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +    private Set<Task> prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime,
Я раньше изучал питон, и теперь я следую его пути, где явное - лучше неявного
Я сейчас работаю с инженерами и выучил главное их правило - работает и ты понимаешь как - не трогай, иначе может стать "не работает и ты не знаешь почему"
И, наконец, я не уверен что знаю, как это правильно использовать после имплементации)

2024-06-16 21:41 UTC, TimurPractic commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +                .min(Comparator.naturalOrder());
Заменил optional на LocalDateTime

2024-06-20 20:10 UTC, Fleaman777 commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +    private Set<Task> prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime,
в данном случае да, возможно наглядней и проще будет использовать твой подход, 
в других проектах, может быть ситуация, когда такие сеты нужно будет создавать в разных местах, и что бы не дублировать схожую логику, ее хорошо определить в одном месте

2024-06-20 20:10 UTC, Fleaman777 commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +            int newId = idSequence++;
да можешь так оставить, не критичный момент)

2024-06-20 20:16 UTC, Fleaman777 commented on src/ru/yandex/practicum/tasktracker/manager/InMemoryTaskManager.java
> +            Optional<LocalDateTime> minStartTime = subtasksStream
понимаю тебя, иногда хочется чуть больше информации, для лучшего понимания, и действительно, в нашем приложении, вынесение в отдельную переменную не сильно скажется на производительности. 
Но прелесть стримов в том, что это как единый организм и все действия в нем плавно перетекают от одного метода к другому, возможно просто нужно время и привычку, что бы стримы так же легко читались, как и какие-нибудь обычные POJO классы. 
Еще помогает хорошо стримы воспринимать, это вынесение логики в разных его частях, в отдельные методы с подходящим названием, которые снимают часть раздумий о том, что именно происходит в условнов filter, map и пр

2024-06-20 20:18 UTC, Fleaman777 approved these changes

2024-06-21 10:33 UTC, merged